### ISSUE TITLE
radare2 support

### ISSUE THREAD

**Issue by Manouchehri** [McGill-DMaS/Kam1n0-Community#12]
Would be interesting to see radare2 support.

Using r2pipe would be my suggested method, it's not too difficult to write plugins. =) 
- https://github.com/radare/radare2-bindings/tree/master/r2pipe
- https://github.com/radare/radare2/wiki/R2PipeAPI
- https://medium.com/@trufae/scripting-r2-with-pipes-47a7e14c50aa#.d7wd5zp2p

**Comment by steven-hh-ding** [comment]
Hi Manouchehri,

Thanks for your suggestion. We also want to extend kam1n0 to other binary analysis frameworks such as capstone or radare2. However, we don't really have enough time to work on it. We need to continue improving Kam1n0 against compilers, CPU architectures, and code obfuscations, etc. Moreover, some request that we should include more information from IDA-Pro which may not be available in the other frameworks. 

Let me know if you or you know someone would like to write such an extension. It won't be difficult to do that at all. Basically Kam1n0 just calls a [script](https://github.com/McGill-DMaS/Kam1n0-Plugin-IDA-Pro/blob/master/Kam1n0WinSetupProject/bin_release/Kam1n0-distribution/ExtractBinaryViaIDA.py) to disassemble; and the whole user interface for IDA Pro plugin can run without IDA by changing [Manager](https://github.com/McGill-DMaS/Kam1n0-Plugin-IDA-Pro/blob/master/Kam1n0WinSetupProject/bin_release/plugins/Kam1n0/Manager.py) and [IDA-utils](https://github.com/McGill-DMaS/Kam1n0-Plugin-IDA-Pro/blob/master/Kam1n0WinSetupProject/bin_release/plugins/Kam1n0/IDAutils.py)

Thanks

**Comment by steven-hh-ding** [comment]
By the way, would you please help us promote our [kam1n0 video](https://twitter.com/bfung123/status/748688218971856896) through your twitter channel? Our papers got accepted in the conference SIGKDD this year and we participate their Audience Appreciation video competition. It is ranked by view count :smiley:. It will help us better serving the reverse engineering community through academia.

**Comment by Manouchehri** [comment]
I'm currently waiting for #2 to be fixed first before I promote (or contribute).

**Comment by steven-hh-ding** [comment]
Hi Manouchehri. We open source the server. I am closing this thread for now. Feel free to open a new one if you are still interested.
