### ISSUE TITLE
 How can i make my tool deko a client for Kam1n0-server ? 

### ISSUE THREAD

**Issue by hackmoonlight** [McGill-DMaS/Kam1n0-Community#13]
this is `deko`
https://github.com/hackmoonlight/deko

**Comment by steven-hh-ding** [comment]
Hi! Thanks for your interest. I don't have a standalone python client yet. But the [Connector](https://github.com/McGill-DMaS/Kam1n0-Plugin-IDA-Pro/blob/master/Kam1n0WinSetupProject/bin_release/plugins/Kam1n0/Connector.py) contains all the necessary details for network connection (login, query, comments ...) and [GetFuncInputSurrogate](https://github.com/McGill-DMaS/Kam1n0-Plugin-IDA-Pro/blob/master/Kam1n0WinSetupProject/bin_release/plugins/Kam1n0/IDAutils.py#L88) construct the format of a query function (as json).

**Comment by steven-hh-ding** [comment]
Hi hackmoonlight. I am closing this thread. Feel free to open another new one if you are still interested.
