### ISSUE TITLE
Using kam1n0 with IDA Demo

### ISSUE THREAD

**Issue by JMoubarak** [McGill-DMaS/Kam1n0-Community#14]
Hello,

I am trying to use Kam1n0 with IDA Demo: I am able to see the interface but I am not able to perform any analysis. Is there a way to fix that?
Also, are we able to test Kam1n0 with IDA Pro free?

Thanks.

**Comment by steven-hh-ding** [comment]
Hi! Currently Kam1n0-plugin is not working with the demo version. One needs to heavily modify the plugin source code. This is currently not a priority in our to-do list.  Thanks!
