### ISSUE TITLE
Any plans to open source Kam1n0 server?

### ISSUE THREAD

**Issue by zaddach** [McGill-DMaS/Kam1n0-Community#16]
Hi,

do you have any plans to release the source of the Kam1n0 server? I would be interested on running it on Linux, which would require some tweaks to the code.

BTW, this is a cool project!

Regards, Jonas

**Comment by steven-hh-ding** [comment]
Hi. Yes we do plan to release the source of server. We are currently under heavy development and research. Things are being changed very day with new features and possibility, thus we want to keep here as a working release.  

For linux, the server itself is just a jar so it shouldn't be difficult to have it running on Linux. But for symbolic mode one needs to re-compile libvex, z3 and the jnit connector on linux. I can share the jnit code with you if you want to do that. 

Thank you!

**Comment by steven-hh-ding** [comment]
Thanks for the help from Jonas. We now have a working release for linux!

**Comment by zaddach** [comment]
Hi Steven,

I'm in Montreal right now for recon. Is there any chance you're still here
and you would have time for a beer? I'm flying out Tuesday.

Jonas

On Apr 20, 2017 09:10, "Steven Ding" <notifications@github.com> wrote:

Thanks for the help from Jonas. We now have a working release for linux!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/McGill-DMaS/Kam1n0-Plugin-IDA-Pro/issues/16#issuecomment-295732394>,
or mute the thread

**Comment by steven-hh-ding** [comment]
Hi Jonas. Yes sure I heard that you have a talk in recon. Congrats! Already PM'd you.


________________________________

**Comment by steven-hh-ding** [comment]
Hi Jonas,

I sent you an email yesterday not sure if you can receive it. Let me know if there is other way I can contact you. Cheers. 

Steven

**Comment by seeker-jtk** [comment]
Hello.

When do you release the source of Kam1n0 server?

Thanks.

**Comment by steven-hh-ding** [comment]
It has been a long time. After finalizing several major changes, we eventually make it to open source the Kam1n0 server, with the same license. Thanks everyone :)

Closing this issue.
