### ISSUE TITLE
IDA Pro 7.0 Support

### ISSUE THREAD

**Issue by mendax47** [McGill-DMaS/Kam1n0-Community#18]
Any News About Supporting IDA Pro 7.0..?

TIA

**Comment by steven-hh-ding** [comment]
Hi TIA! We are currently working on a new release 2.x. We will probably work on its IDA Pro 7.0 plugin after this release. For now, we don't have any plan to support the 1.x version for IDA Pro 7. Release 2.x will be very different and released soon.

**Comment by mendax47** [comment]
Hello Steven... Can You Give ME Any Idea About The Release Date Of Your V2.x?

**Comment by steven-hh-ding** [comment]
Hi TIA. It is already done. All repositories managed in single app. Support IDA 6.8+. I don't have a specific time yet. But probably this December.

**Comment by steven-hh-ding** [comment]
@mendax47 v2 pre-release is out. completely redesigned. It takes longer than we expected. ;)
