### ISSUE TITLE
Question about architecture

### ISSUE THREAD

**Issue by dummys** [McGill-DMaS/Kam1n0-Community#3]
Hi, your stuff looks promising. What about architecture ? there is not only x86 is the world :D Did you plan tu support MIPS, ARM ?

**Comment by bcmfung** [comment]
Hello,

Thank you. We will take the architecture into consideration in our future
version. Yet, we have very limited resources in this project at the moment.

Regards,
Benjamin

Benjamin Fung ben.fung@mcgill.ca
Canada Research Chair in Data Mining for Cybersecurity
Associate Professor, School of Information Studies
McGill University, Montreal, Canada
http://dmas.lab.mcgill.ca/fung
Tel: 514-3983360

**Comment by steven-hh-ding** [comment]
Hello. The new version now supports arm and powerpc. We haven't got enough time to work on mips yet. It can be added following our tutorial - [create your own processor definition](https://github.com/McGill-DMaS/Kam1n0-Plugin-IDA-Pro/blob/master/documentation/processor-definition.md#create-your-own-processor-definition)
