### ISSUE TITLE
IDA Pro won't communicate with Kam1n0

### ISSUE THREAD

**Issue by praseodym** [McGill-DMaS/Kam1n0-Community#5]
Uploading a new file for indexing through the web interface works fine, but I can't seem to get IDA Pro to talk to the Kam1n0 server. For index and search operations, I end up with the following error:

![kam1n0-error](https://cloud.githubusercontent.com/assets/20283/10281187/f25292b8-6b72-11e5-986c-f96f4f074a14.PNG)

There are no error messages in the Kam1n0 console, and I'm not sure where else to look for log messages.

**Comment by steven-hh-ding** [comment]
Hi praseodym. Can you open the admin page through IDA Pro? Are you running Kam1n0 and IDA-Pro on the same machine?  Please review your connection settings in IDA Pro and make sure it points to Kam1n0. Thanks!

**Comment by praseodym** [comment]
If I click 'Manage storage', the admin page pops up (although I do have to log in, which works fine). In 'Manage connections', everything is set up correctly. I'm running IDA Pro and Kam1n0 on the same machine so I'm just pointing IDA Pro to `http://127.0.0.1:9988` with `admin`:`admin` as login info.

**Comment by steven-hh-ding** [comment]
Hi Parseodym,

Sorry for getting back to you so late. I was working on a new release. Could you provide me more detail for me to reproduce the error? 

Thanks,

Steven

**Comment by praseodym** [comment]
No problem. The web interface works fine, however IDA Pro doesn't talk to the Kam1n0 server. The error in my first post is the only thing I see whenever I try to use Kam1n0 integration from IDA Pro (e.g. when I try to index or search a function). There are no errors logged to the IDA console either.

**Comment by steven-hh-ding** [comment]
Could I have your OS version and IDA Pro version?

**Comment by praseodym** [comment]
Windows 7 x64 with IDA Pro 6.8.150428.

**Comment by steven-hh-ding** [comment]
Hi there is a problem for Kam1n0 to work with IDA Pro 6.8. Gonna fix it with the next release this month. Thank you.

**Comment by praseodym** [comment]
That explains, thanks!

**Comment by steven-hh-ding** [comment]
The new version should resolve this problem.
