### ISSUE TITLE
Warning Massage In IDA Pro 6.8

### ISSUE THREAD

**Issue by mendax47** [McGill-DMaS/Kam1n0-Community#6]
I Am Getting This Warning...
C:/Program File (x86)/IDA 6.8/Plugins\Kam1n0\Forms\SelectionForm.py:130: SyntexWarning: name 'allFuncs' is used prior to global declaration

C:/Program File (x86)/IDA 6.8/Plugins\Kam1n0\Forms\SelectionFormIndex.py:140: SyntexWarning: name 'allFuncs' is used prior to global declaration

How To Solve It...?

**Comment by steven-hh-ding** [comment]
Hi Mendax47,

We are working on a new release of the plugin as well as the engine. Hopefully it will be available later this month. Could you provide more details for me to reproduce the error? It works fine on both win7, win8, and win10 vm with a clean installation. 

Cheers,

Steven

**Comment by steven-hh-ding** [comment]
Hi, it turns out that the plugin is not working well with IDA v6.8. I am fixing it. Thanks.

**Comment by steven-hh-ding** [comment]
The new version should resolve this problem.
